force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;None Specified&quot;</defaultValue>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Cherokee</fullName>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergy &amp; Immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Diagnostic Radiology</fullName>
            </value>
            <value>
                <fullName>Emergency Medicine</fullName>
            </value>
            <value>
                <fullName>Family Medicine</fullName>
            </value>
            <value>
                <fullName>Internal Medicine</fullName>
            </value>
            <value>
                <fullName>Medical Genetics</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Nuclear Medicine</fullName>
            </value>
            <value>
                <fullName>Obstetrics and Gynecology</fullName>
            </value>
            <value>
                <fullName>Ophthamology</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Physical Medicine &amp; Rehabilitation</fullName>
            </value>
            <value>
                <fullName>Preventative Medicine</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Radiation Oncology</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DoctorFactory.cls
// Generates a bunch of contacts of type Doctor for testing
// Doesn't enable them as partners or anything, just connects them to Southern Heart
public class DoctorFactory 
{	// All doctors will be contacts of the account SouthernHeart
    static Account SouthernHeart = 	[ 	SELECT Id 
                             			FROM Account 
                             			WHERE Name = 'Southern Heart' 
                            		] [0];
    // PicklistEntry lists have namespaces for easy reference
    static List<PicklistEntry> specialties = Contact.Specialty__c.getDescribe().getPicklistValues();
    static List<PicklistEntry> languages = Contact.Language__c.getDescribe().getPicklistValues();
    static List<PicklistEntry> genders = Contact.Gender__c.getDescribe().getPicklistValues();
    
	public static List<Contact> generate ( Integer drCount )
    {
        List<Contact> newDocs = new List<Contact>();
        for ( Integer i = 0 ; i < drCount ; i++ )
        {	Contact dr = new Contact( 	FirstName = 'Roy', 
                                     	LastName = 'Disney the ' + i + 'st'
                                    );
       		dr.AccountID = SouthernHeart.Id;
           	dr.Type__c = 'Doctor';
            dr.Specialty__c = specialties[ Integer.valueOf( Math.random() * specialties.size() ) ].getValue();
			dr.Language__c = languages[ Integer.valueOf( Math.random() * languages.size() ) ].getValue();
            dr.Gender__c = genders[ Integer.valueOf( Math.random() * genders.size() ) ].getValue();
            newDocs.add(dr);
        }
        insert newDocs;
        return newDocs;
    }
    
    public static void Cleanup()
    {	delete [	SELECT id 
                	FROM Contact 
                	WHERE FirstName = 'Roy' 
                	AND LastName LIKE 'Disney the %th'
               ];
        
    }
}