force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Test for VS Code.</description>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/AppointmentContacts__c.field-meta.xml
<CustomField>
    <fullName>AppointmentContacts__c</fullName>
    <description>Each AppointmentContacts can have multiple Appointments.  This lets Contacts accessing the junction object look at Roll-Up Summaries of all Appointmetns and related Contacts.</description>
    <label>AppointmentContacts</label>
    <referenceTo>AppointmentContacts__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Appointment begins on this day at this hour.</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AppointmentContacts__c/AppointmentContacts__c.object-meta.xml
<CustomObject>
    <description>Junction object for relating Appointments to Contacts.  Each Contact has a Master-Detail Relationship to AppointmentContacts that allows us to acquire two related contacts (1 Doctor and 1 Patient) per appointment.  Each Appointment has a Master-Detail relationship to AppointmentContacts that that allows us to access appointments as a roll-up summary.</description>
    <label>AppointmentContacts</label>
    <nameField>
        <label>AppointmentContacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppointmentContacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AppointmentContacts__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <description>Appointment can call Roll-Up Summaries of each AppointmentContact&#39;s unique Contact.  This lets Appointments track doctors and patients.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>AppointmentContacts</relationshipLabel>
    <relationshipName>AppointmentContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AppointmentContacts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>AppointmentContact is related to a unique Contact.  When a patient or doctor creates an Appointment, they&#39;re also creating two AppointmentContacts linked to that Appointment (one linked to themself, the other to their medical interlocutor).</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AppointmentContacts</relationshipLabel>
    <relationshipName>AppointmentContacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <defaultValue>&quot;None Specified&quot;</defaultValue>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Cherokee</fullName>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergy &amp; Immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Diagnostic Radiology</fullName>
            </value>
            <value>
                <fullName>Emergency Medicine</fullName>
            </value>
            <value>
                <fullName>Family Medicine</fullName>
            </value>
            <value>
                <fullName>Internal Medicine</fullName>
            </value>
            <value>
                <fullName>Medical Genetics</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Nuclear Medicine</fullName>
            </value>
            <value>
                <fullName>Obstetrics and Gynecology</fullName>
            </value>
            <value>
                <fullName>Ophthamology</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
            <value>
                <fullName>Physical Medicine &amp; Rehabilitation</fullName>
            </value>
            <value>
                <fullName>Preventative Medicine</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Radiation Oncology</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AppointmentFactory.cls
// Generates a bunch of appointments attached to currently existing contacts
// You have to make an object of this class for it to work, since it uses contacts on construction
// Definitely run the cleanup method ASAP.  It randomly assigns appointments between all drs and patients
// in the db!
public class AppointmentFactory 
{
    static final String dcode = 'DELETE ME LATER';
    static Account SouthernHeart = 	[ 	SELECT Id 
                             			FROM Account 
                             			WHERE Name = 'Southern Heart' 
                            		] [0];
    List<Contact> drs;	// initialized in the constructor to all drs
    List<Contact> pats;	// initialized in the constructor to all patients
    
    public AppointmentFactory()
    {
        drs = [ SELECT Id, FirstName, LastName, Email, Phone, Specialty__c, Language__c, Gender__c
               	FROM Contact
               	WHERE Type__c = 'Doctor'
              ];
        pats = 	[	SELECT Id, FirstName, LastName, Email, Phone
              		FROM Contact
                	WHERE Type__c = 'Patient'
              	];
    }
    
    public List<Appointment__c> generate ( Integer count )
    {   // initialize appts and junctions
        List<Appointment__c> appts = new List<Appointment__c>();
        List<AppointmentContacts__c> appcons = new List<AppointmentContacts__C>();
        for ( Integer i = 0 ; i < count ; i++ )
        {   // add new appointment
            Appointment__c a = new Appointment__c( Name = dcode );
        	a.Start_Time__c = System.today().addDays(7);
         	a.Status__c = 'Pending';
         	appts.add(a);
            insert a;
            // add junctions assigning drs and patients to appts
            AppointmentContacts__c dr = new AppointmentContacts__c( Name = dcode );
            dr.Appointment__c = a.Id;
            dr.Contact__c = drs[ Integer.valueOf( Math.random() * drs.size() ) ].Id;
            AppointmentContacts__c pat = new AppointmentContacts__c( Name = dcode );
            pat.Appointment__c = a.Id;
            pat.Contact__c = pats[ Integer.valueOf( Math.random() * pats.size() ) ].Id;
            appcons.add(dr); appcons.add(pat);
        }
        insert appcons;
        return appts;
    }
    public void cleanup()
    {
        delete 	[	SELECT id FROM Appointment__c WHERE Name = : dcode ];
        delete 	[	SELECT id FROM AppointmentContacts__c WHERE Name = : dcode ];
    }

}