force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Test for VS Code.</description>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/AppointmentContacts__c.field-meta.xml
<CustomField>
    <fullName>AppointmentContacts__c</fullName>
    <description>Each AppointmentContacts can have multiple Appointments.  This lets Contacts accessing the junction object look at Roll-Up Summaries of all Appointmetns and related Contacts.</description>
    <label>AppointmentContacts</label>
    <referenceTo>AppointmentContacts__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Appointment begins on this day at this hour.</description>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AppointmentContacts__c/AppointmentContacts__c.object-meta.xml
<CustomObject>
    <description>Junction object for relating Appointments to Contacts.  Each Contact has a Master-Detail Relationship to AppointmentContacts that allows us to acquire two related contacts (1 Doctor and 1 Patient) per appointment.  Each Appointment has a Master-Detail relationship to AppointmentContacts that that allows us to access appointments as a roll-up summary.</description>
    <label>AppointmentContacts</label>
    <nameField>
        <label>AppointmentContacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppointmentContacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AppointmentContacts__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <description>Appointment can call Roll-Up Summaries of each AppointmentContact&#39;s unique Contact.  This lets Appointments track doctors and patients.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipLabel>AppointmentContacts</relationshipLabel>
    <relationshipName>AppointmentContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AppointmentContacts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>AppointmentContact is related to a unique Contact.  When a patient or doctor creates an Appointment, they&#39;re also creating two AppointmentContacts linked to that Appointment (one linked to themself, the other to their medical interlocutor).</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AppointmentContacts</relationshipLabel>
    <relationshipName>AppointmentContacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DoctorHomeController.cls
public class DoctorHomeController 
{   public String currentId { get ; set ; }
    public List<AppointmentContacts__c> patients { get ; set ; }
    private string status='';
    User currUser;
    Contact currContact;

    public DoctorHomeController () 
    {	currUser = 	[	Select Id, ContactId 
                     	from User 
                     	where Id = :UserInfo.getUserId() 
                    ];
        //currContact = [ SELECT Id FROM Contact WHERE Id = :currUser.ContactID ];
        // For the purpose of testing, set current contact to Roy Disney
        currContact = [ SELECT Id FROM Contact WHERE Name = 'Roy Disney the 0st'];
		getAppointment();
    }
    
    public void allStatus(){
       status='';
       getAppointment();
    }
    
    public void Pending()
    {  	status='Pending';
       	getAppointment();
    }
    public void Completed()
    {  	status='Completed';
  		getAppointment();
    }
    
    public void Rejected()
    {   status='Rejected';
        getAppointment();
    }
    public void Confirmed()
    { 	status='Confirmed';
      	getAppointment();
    }
    public void accept(){
    	System.debug('Check out this cool ID: ' + currentID);
        updateStatus('Confirmed');
        getAppointment();
    }
    public void reject(){
		updateStatus('Rejected');
        status='';
        getAppointment();
    }
    
 	// Call this method to update the page and refetch results
  	private  void getAppointment()
    {	// make a list of appointment junctions involving current user
        List<AppointmentContacts__c> doctorApps = 	
        [ 	SELECT Appointment__r.id
          	FROM AppointmentContacts__c 
           	WHERE Contact__r.Id = :currContact.Id
        ];
        // make a list of IDs for those junctions
        List<ID> groundhog = new List<ID>();
        for ( AppointmentContacts__c app : doctorApps ) 
        	groundhog.add(app.Appointment__r.id);
        // make a list of apppointment junctions on the other side of appointment
        patients = 
        [	SELECT 	Id, Appointment__r.Id, Appointment__r.Start_Time__c, Appointment__r.Status__c,
           			Contact__r.Id, Contact__r.Name, Contact__r.Phone, Contact__r.Email
           	FROM AppointmentContacts__c
          	WHERE Appointment__r.Id IN :groundhog	// same appointment the doctor is in
         	AND Contact__r.Id != :currContact.Id	// contact to be listed is not the doctor
         	AND Appointment__r.Status__c LIKE :status+'%'
        ];
    }
        
  public void updateStatus(String newStatus)
  {   
      for ( AppointmentContacts__c curr: 
           [	SELECT id, Appointment__r.id, Appointment__r.Status__c
                FROM AppointmentContacts__c
                WHERE id=:currentId
           ]
          )
      {	  System.debug('You have selected appointment: ' + curr.id);
          curr.Appointment__r.status__c = newStatus;
          update curr.Appointment__r;
      }
               
                                  
    }
    public pagereference logout()
    {
       //perform Business logic here
        PageReference pageRef = new PageReference('/default/secur/logout.jsp');
        pageRef.setRedirect(true);
        return pageRef;
    }
   
    
}